EMS.Website/Controllers/RoleController.cs
using System;
using System.Linq;
//using System.Web.Mvc;
using EMS.Data;
using EMS.Service;
using EMS.Web.Code.Attributes;
//using DataTables.AspNet.Core;
using EMS.Core;
//using EMS.Web.Code.LIBS;
using EMS.Dto;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EMS.Web.Controllers
{
    [CustomAuthorization()]
    public class RoleController : BaseController
    {
        #region "Fields"       
        private IRoleService roleServices;
        #endregion

        #region "Constructor"
        public RoleController(IRoleService roleServices)
        {
            this.roleServices = roleServices;

        }
        #endregion

      [CustomActionAuthorization]
        [HttpGet]
        public ActionResult Index()
        {
            RoleDto roleDto = new RoleDto();
           

            List<RoleCategory> roleCategoryList = roleServices.GetActiveRoleCategory();
            roleDto.roleCategoryList = roleServices.GetActiveRoleCategory().Select(x => new DropdownListDto { Text = x.Name, Id = x.Id }).ToList();

            


            List<Role> roleList = roleServices.GetActiveRoles();
            roleDto.RoleList = roleServices.GetActiveRoles().Select(x => new DropdownListDto { Text = x.RoleName, Id = x.RoleId }).ToList();



            List<Designation> designationList = roleServices.GetDesignationList();
            roleDto.designationList = roleServices.GetDesignationList().Select(x => new DropdownListDto { Text = x.Name, Id = x.Id }).ToList();



            return View(roleDto);
        }

      [CustomActionAuthorization]
        [HttpGet]
        public ActionResult MenuAccess(int roleId, int designationId)
        {
            RoleDto roleDto = new RoleDto();

            var data = roleServices.GetRoleById(roleId);
            roleDto.RoleName = data.RoleName;
            roleDto.RoleId = data.RoleId;
          //  roleDto.DesignationId = data.Designation.I;
            //roleDto.RoleCateGoryId = data.RoleCategory.Id;
            roleDto.Status = data.IsActive.HasValue ? data.IsActive.Value : false;

            roleDto.ParentMenu = roleServices.GetParentMenu().Select(x => new ParentMenuLDto { MenuId = x.MenuId, MenuDisplayName = Regex.Replace(x.MenuDisplayName, @"\s", "") }).ToList();

            var itemList = roleDto.ParentMenu.Select(x => x.MenuId).ToList();

            roleDto.AllMenu = roleServices.GetFrontMenuByIds(itemList).Select(x => new AllMenuDto { MenuDisplayName = x.MenuDisplayName.Trim(), MenuId = x.MenuId, ParentId = x.ParentId.HasValue ? x.ParentId.Value : 0 }).ToList();

            roleDto.ChildMenuList = roleServices.GetChildMenu(roleId, designationId).Select(x => new ChildMenuLDto { MenuDisplayName = x.FrontMenu.MenuDisplayName.Trim(), MenuId = x.FrontMenu.MenuId, ParentId = x.FrontMenu.ParentId.HasValue ? x.FrontMenu.ParentId.Value : 0 }).ToList();


            roleDto.RoleList = roleServices.GetActiveRoles().Select(x => new DropdownListDto { Text = x.RoleName, Id = x.RoleId }).ToList();

            return View("_MenuAccess", roleDto);
        }
        [HttpPost]

        public ActionResult SaveRecords(RoleDto roleData)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    roleServices.DeleteList(roleData);
                    if (roleData.childmenu != null)
                    {
                        roleServices.SaveList(roleData);
                    }
                    return NewtonSoftJsonResult(new RequestOutcome<string> { RedirectUrl = Url.Action("index", "role"), Message = "Record saved successfully.", IsSuccess = true });
                }
            }
            catch (Exception ex)
            {
                string message = ex.GetBaseException().Message;
                ModelState.AddModelError("Error!", message);
            }
            return CreateModelStateErrors();
        }


        [HttpGet]
        public ActionResult BindRoleList(int? RoleCateGoryId)
        {
            var ddlRole = roleServices.GetRolesByRoleCategoyId(RoleCateGoryId ?? 0);
            var ddlRoleList = ddlRole.Select(x => new SelectListItem() { Text = x.RoleName, Value = x.RoleId.ToString() }).ToList();
            ddlRoleList.Insert(0, new SelectListItem() { Text = "-Select-", Value = "" });

            var response = new
            {
                RoleList = ddlRoleList,
            };


            return Json(response);

        }

        [HttpGet]
        public ActionResult BindDesignationList(int? RoleId)
        {
            var ddlDesignation = roleServices.GetDesignationByRoleId(RoleId ?? 0);
            var ddlDesignationList = ddlDesignation.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList();
            ddlDesignationList.Insert(0, new SelectListItem() { Text = "-Select-", Value = "" });

            var response = new
            {
                DesignationList = ddlDesignationList,
            };
            return Json(response);

        }

    }
}

EMS.Website/Views/Role/Index.cshtml
@using EMS.Web.Models.Others
@model EMS.Dto.RoleDto
@using EMS.Core
<style>
    .clsSmallFont {
        font-size: xx-small;
    }

    .menuaccuss_editable {
        margin-top: 20px;
    }

    .customCombobox {
        width: 200px;
        margin: 0;
        padding: 0;
        cursor: pointer;
        align-content: center;
    }
</style>
<div class="main_content clearfix">
    <div class="full-wdth clearfix padding20">
        <div class="timesheet-page full-wdth clearfix">
            <div id="RoleMessageDiv" class="alert alert-success alert-dismissable" style="display:none"></div>
            <h2> Manage Role </h2>
            <div class="validation-summary"></div>
            <div class="create-form-outer-box dis-block clearfix">
                <div class="form-wdth1 dis-block clearfix">
                    <div class="grey-bg ems-form checkList-outer dis-block clearfix">
                        @using (Html.BeginForm("SaveRecords", "Role", FormMethod.Post, new { @id = "form1" }))
                        {


                            <div class="row">

                                <div class="col-md-6">
                                    <div class="col-md-6">
                                        <label>Role Category:</label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(model => model.RoleCateGoryId, new SelectList(Model.roleCategoryList, "Id", "Text"), "-Select-", new { @class = "form-control", @data_msg_required = "* Required", @data_rule_required = "true" })
                                    </div>
                                </div>
                                <div class="col-md-6"></div>


                            </div>
                            <div class="row">

                                <div class="col-md-6">
                                    <div class="col-md-6">
                                        <label>Role Name:</label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(model => model.RoleId, new SelectList(Model.RoleList, "Id", "Text"), "-Select-", new { @class = "form-control", @data_msg_required = "* Required", @data_rule_required = "true" })
                                    </div>
                                </div>
                                <div class="col-md-6"></div>


                            </div>
                            <div class="row">

                                <div class="col-md-6">
                                    <div class="col-md-6">
                                        <label>Designation :</label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(model => model.DesignationId, new SelectList(Model.designationList, "Id", "Text"), "-Select-", new { @class = "form-control", @data_msg_required = "* Required", @data_rule_required = "true" })
                                    </div>
                                </div>
                                <div class="col-md-6"></div>
                            </div>
                            <div class="row menuaccuss_editable"></div>
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-custom pull-right margin-right10" name="Save">Update</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="divoverlay hide"></div>

@section scripts{
    <script src="/Scripts/CustomJS/Role.js">
    </script>
}

EMS.Website/Views/Role/_MenuAccess.cshtml
@using EMS.Web.Models.Others
@model EMS.Dto.RoleDto
@using EMS.Core
@{
    Layout = null;
}
<div class="menuaccuss_editable">
    <div class="col-sm-12">
        <ul class="nav nav-tabs">
            @foreach (var parentmenu in Model.ParentMenu)
            {
                int index = Model.ParentMenu.IndexOf(parentmenu);
                if (index == 0)
                {
                    <li class="active"><a data-toggle="tab" href="#@parentmenu.MenuDisplayName.Trim()">@parentmenu.MenuDisplayName</a></li>
                }
                else
                {
                    <li><a data-toggle="tab" href="#@parentmenu.MenuDisplayName.Trim()">@parentmenu.MenuDisplayName</a></li>
                }
            }
        </ul>
        <div class="tab-content">
            @foreach (var parentmenu in Model.ParentMenu)
            {
                if (Model.ParentMenu.IndexOf(parentmenu) == 0)
                {
                    <div id="@parentmenu.MenuDisplayName.Trim()" class="tab-pane fade in active">
                        @foreach (var allmenu in Model.AllMenu.Where(x => x.ParentId == parentmenu.MenuId && Model.ParentMenu.IndexOf(parentmenu) == 0))
                        {
                            <div class="col-md-3 checkList">
                                <div style="float:left;">
                                    <input type="checkbox" name="childmenu" id="chkchildmenu_@allmenu.MenuId" @(Model.ChildMenuList.Any(a => a.MenuId == allmenu.MenuId) ? "checked" : "") data-id="@allmenu.MenuId" value="@allmenu.MenuId" />
                                    <label for="chkchildmenu_@allmenu.MenuId">   &nbsp;@allmenu.MenuDisplayName</label>
                                </div>
                            </div>
                        }
                    </div>
                }
                else
                {
                    <div id="@parentmenu.MenuDisplayName.Trim()" class="tab-pane fade">
                        @foreach (var allmenu in Model.AllMenu.Where(x => x.ParentId == parentmenu.MenuId && Model.ParentMenu.IndexOf(parentmenu) > 0))
                        {
                            <div class="col-md-3 checkList">
                                <div style="float:left;">
                                    <input type="checkbox" name="childmenu" id="chkchildmenu_@allmenu.MenuId" @(Model.ChildMenuList.Any(a => a.MenuId == allmenu.MenuId) ? "checked" : "") data-id="@allmenu.MenuId" @*id="chkTech_@tech.Id"*@ value="@allmenu.MenuId" />
                                    <label for="chkchildmenu_@allmenu.MenuId">   &nbsp;@allmenu.MenuDisplayName</label>
                                </div>
                            </div>
                        }
                    </div>
                }
            }
        </div>
    </div>
</div>