EMS.Website/Controllers/WFHController.cs
using EMS.Dto;
using EMS.Dto.SARAL;
using EMS.Service.SARAL;
using EMS.Service.SARALDT;
using EMS.Service;
using EMS.Web.Code.Attributes;
using EMS.Web.Code.LIBS;
using EMS.Web.Models;
using EMS.Web.Models.Calendar;
using EMS.Web.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using static EMS.Core.Enums;
using EMS.Website.Code.LIBS;
using System.Linq.Expressions;
using System.Data;
using System.Net;
using EMS.Website.Models;
using DataTables.AspNet.Core;
using EMS.Data;
using EMS.Data.Model;
using EMS.Core;
using System.IO;
using EMS.Website.LIBS;

namespace EMS.Website.Controllers
{
    public class WFHController : BaseController
    {
        #region "Fields"       
        private IUserLoginService userLoginService;
        private IWFHService WFHService;
        private ILeaveService leaveService;
        string logPath = "D:/local/EMSWebCore/EMS.Website/wwwroot/WFH_Log/wfh-log.txt";
        #endregion

        #region "Constructor"       
        public WFHController(IUserLoginService _userLoginService, IWFHService _manageWFHService, ILeaveService _leaveService)
        {
            this.userLoginService = _userLoginService;
            this.WFHService = _manageWFHService;
            this.leaveService = _leaveService;

        }
        #endregion


        #region "HttpGet-ManageWFH"
        /// <summary>
        /// ManageWFH Get method use to get WFH request details
        /// </summary>
        /// <param name="returnview"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ManageWFH(string returnview, int? id)
        {            
            ViewBag.ReturntoListView = (returnview != null ? (returnview.ToLower().Trim() != "calendar") : true);
            bool IsEdit = id != null && id > 0 ? true : false;
            bool IsPmHrPmo = (RoleValidator.HR_RoleIds.Contains(CurrentUser.RoleId) || CurrentUser.RoleId == (int)Enums.UserRoles.PM || CurrentUser.RoleId == (int)Enums.UserRoles.UKPM || CurrentUser.RoleId == (int)Enums.UserRoles.PMO
                           || RoleValidator.TL_Technical_DesignationIds.Contains(CurrentUser.DesignationId)
                           || RoleValidator.TL_QualityAnalyst_DesignationIds.Contains(CurrentUser.DesignationId)
                           || RoleValidator.TL_DigitalMarketing_DesignationIds.Contains(CurrentUser.DesignationId)
                           || RoleValidator.TL_UIUX_DesignationIds.Contains(CurrentUser.DesignationId)
                           || RoleValidator.TL_ARVRUnityGaming_DesignationIds.Contains(CurrentUser.DesignationId)
                           || RoleValidator.TL_Sales_DesignationIds.Contains(CurrentUser.DesignationId)
                           || RoleValidator.TL_ITInfra_DesignationIds.Contains(CurrentUser.DesignationId)
                           || RoleValidator.TL_AccountsandAdmin_DesignationIds.Contains(CurrentUser.DesignationId)
                           || RoleValidator.TL_HR_DesignationIds.Contains(CurrentUser.DesignationId)
                           || CurrentUser.RoleId == (int)Enums.UserRoles.UKBDM) ? true : false;
            Dictionary<string, string> hdnFields = new Dictionary<string, string>();
            Wfhactivity wfhDB = new Wfhactivity();
            WFHActivityDto wfhDto = new WFHActivityDto();
            hdnFields.Add("returnview", returnview ?? "");


            if (RoleValidator.HR_RoleIds.Contains(CurrentUser.RoleId))
            {
                ViewBag.PMList = userLoginService.GetPMAndPMOHRDirectorUsers().Select(p => new SelectListItem { Text = p.Name, Value = p.Uid.ToString() }).ToList();
            }
            try
            {
                if (IsEdit)
                {
                    #region "Binding Data Model to View Model"

                    wfhDB = WFHService.GetWFHById(id.Value);
                    wfhDto.Uid = wfhDB.Uid;
                    wfhDto.PMid = wfhDB.U.PMUid.HasValue ? wfhDB.U.PMUid.Value : 0;
                    wfhDto.userId = wfhDB.Uid;
                    wfhDto.WFHId = wfhDB.Wfhid;
                    wfhDto.StartDate = wfhDB.StartDate != null ? wfhDB.StartDate.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture) : null;
                    wfhDto.EndDate = wfhDB.EndDate != null ? wfhDB.EndDate.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture) : null;
                    wfhDto.Comment = wfhDB.Comment;
                    wfhDto.IsHalf = wfhDB.IsHalf != null ? wfhDB.IsHalf.Value : false;
                    wfhDto.DateAdded = wfhDB.DateAdded ?? DateTime.Now;
                    wfhDto.DateModify = wfhDB.DateModify ?? DateTime.Now;
                    wfhDto.Status = wfhDB.Status ?? 0;
                    wfhDto.IP = GeneralMethods.Getip();
                    wfhDto.IsCancel = (wfhDto.Status == (int)WFHStatus.Cancelled);
                    wfhDto.IsSelfWFH = wfhDB.Uid == CurrentUser.Uid;
                    wfhDto.FirstHalf = wfhDB.FirstHalf != null ? (bool)wfhDB.FirstHalf ? true : false : false;
                    wfhDto.SecondHalf = wfhDB.SecondHalf != null ? (bool)wfhDB.SecondHalf ? true : false : false;
                    wfhDto.HalfValue = wfhDB.FirstHalf == true ? 1 : wfhDto.SecondHalf == true ? 2 : 0;
                    hdnFields.Add("hdnTLId", wfhDB.U.TLId.ToString());
                    hdnFields.Add("hdnAddDT", wfhDB.DateAdded.ToString() ?? DateTime.Now.ToString("dd/MM/yyyy"));

                    #endregion
                }
                else
                {
                    wfhDto.WFHCategory = (int)Enums.WFHCategory.Full;
                    wfhDto.Status = (int)WFHStatus.Pending;
                    hdnFields.Add("hdnTLId", CurrentUser.TLId.ToString());
                    hdnFields.Add("hdnAddDT", DateTime.Now.ToString("dd/MM/yyyy"));
                    wfhDto.userId = 0;
                }
                wfhDto.selectEmployeeList = IsPmHrPmo ? GetEmployees() : null;
                var halfType = new List<SelectListItem>() { new SelectListItem { Text = "First Half", Value = "1" }, new SelectListItem { Text = "Second Half", Value = "2" } };
                halfType.Insert(0, new SelectListItem() { Text = "-Select-", Value = "" });
                wfhDto.HalfType = halfType;
                ViewBag.HdnFields = hdnFields;
            }
            catch (Exception ex)
            {
            }
            wfhDto.IsAllowWFH = true;

            var pmId = (CurrentUser.RoleId == (int)Enums.UserRoles.PM ? CurrentUser.Uid : CurrentUser.PMUid);

            

            if (pmId > 0)
            {
                var _prefereces = leaveService.GetPreferecesByPMUid(pmId);
                if (_prefereces != null)
                {
                    if (_prefereces.IsAllowWFHByTL && CurrentUser.RoleId != (int)Enums.UserRoles.PM)
                    {
                        wfhDto.IsAllowWFH = false;
                    }
                }
            }
            return View(wfhDto);
        }
        #endregion

        #region GetEmployees List
        /// <summary>
        /// GetEmployees method use to get list of all Employees.
        /// </summary>
        /// <param name="selectDefault"></param>
        /// <returns></returns>
        private List<SelectListItem> GetEmployees(bool selectDefault = true)
        {
            var EmployeeList = userLoginService.GetUsersListByAllDesignation(CurrentUser.Uid, CurrentUser.RoleId, CurrentUser.DesignationId);
            var selectEmpList = EmployeeList.Select(x => new SelectListItem { Text = x.Name.ToString(), Value = x.Uid.ToString(), Selected = selectDefault ? (x.Uid == EmployeeList.FirstOrDefault().Uid ? true : false) : false }).ToList();
            if (selectDefault)
                selectEmpList.Insert(0, new SelectListItem() { Text = "-Select-", Value = "" });
            return selectEmpList;
        }

        [HttpPost]
        public ActionResult GetEmployeesByPM(int pmid)
        {
            var users = (pmid > 0 ? userLoginService.GetUsersByPM(pmid) : userLoginService.GetUsers(true)).Select(u => new { text = u.EmpCode != null ? u.Name.ToString() + " [" + u.EmpCode + "]" : u.Name, value = u.Uid });
            return Json(users);
        }

        public ActionResult GetEmployeesByHR()
        {
            List<UserLogin> userList;
            int pmid = (CurrentUser.RoleId == (int)Enums.UserRoles.PM || CurrentUser.RoleId == (int)Enums.UserRoles.PMO || CurrentUser.RoleId == (int)Enums.UserRoles.HRBP) ? CurrentUser.Uid : CurrentUser.PMUid;
            bool IsHRUserRole = CurrentUser.RoleId == (int)Enums.UserRoles.HRBP;
            if (IsHRUserRole)
            {
                userList = userLoginService.GetWorkAlternators(pmid, CurrentUser.Uid, (int)Enums.UserRoles.HRBP);
            }
            else
            {
                userList = userLoginService.GetUsersByPM(pmid);
            }

            var users = userList.Select(u => new { text = u.EmpCode != null ? u.Name.ToString() + " [" + u.EmpCode + "]" : u.Name, value = u.Uid });
            return Json(users);
        }
        #endregion

        #region "HttpPost-ManageWFH"
        /// <summary>
        /// ManageWFH post method is use to save WFH request details.
        /// </summary>
        /// <param name="wfhModelForm"></param>
        /// <param name="returnview"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ManageWFH(WFHActivityDto wfhModelForm, string returnview)
        {
            var fileLogPath = SiteKey.IsLive ? System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "WFH_Log", "wfh-log.txt") : logPath;
            try
            {                
                var modalStartDate = DateTime.ParseExact(wfhModelForm.StartDate.Trim(), "dd/MM/yyyy", CultureInfo.InvariantCulture);

EMS.Website/Views/WFH/Index.cshtml
@using EMS.Data;
@using EMS.Core;
@model IEnumerable<Wfhactivity>
@{
    ViewBag.Title = "Manage WFH";
}

<div class="main_content">
    <div class="full-wdth padding20">
        @await Html.PartialAsync("_Notification")
        <div class="row margin-bottom20">
            <div class="col-sm-3">
                <h2>Manage - Work From Home</h2>
            </div>
            <div class="col-sm-9 pull-right">
                <div class="row">
                    @Html.ActionLink("Apply WFH", "manageWFH", "WFH", null, new { @class = "btn btn-custom pull-right margin-right10 btnlistview" })

                    <div class="col-md-2 pull-right"></div>
                    <div class="col-md-2 pull-right">@Html.DropDownList("status", (List<SelectListItem>)ViewBag.Status, "-Status-", new { @class = "m-wrap medium form-control searchfilter" })</div>
                                       
                    
                    @if (RoleValidator.HR_RoleIds.Contains(CurrentUser.RoleId) || CurrentUser.RoleId == (int)Enums.UserRoles.PM || CurrentUser.RoleId == (int)Enums.UserRoles.UKPM || CurrentUser.RoleId == (int)Enums.UserRoles.PMO
                      || RoleValidator.TL_Technical_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_QualityAnalyst_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_DigitalMarketing_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_UIUX_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_ARVRUnityGaming_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_ITInfra_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_Sales_DesignationIds.Contains(CurrentUser.DesignationId)
                      //|| RoleValidator.DV_RoleIds.Contains(CurrentUser.RoleId) 
                      || CurrentUser.RoleId == (int)Enums.UserRoles.UKBDM)
                    {
                        if (ViewBag.Users != null)
                        {
                            if (ViewBag.Users.Count > 0)
                            {
                               <div class="col-md-2 pull-right">
                                   @Html.DropDownList("user", (List<SelectListItem>)ViewBag.Users, "All Employee", new { @class = "m-wrap medium form-control searchfilter" })
                               </div>

                                if (RoleValidator.HR_RoleIds.Contains(CurrentUser.RoleId))
                                {
                            <div class="col-md-2 pull-right">
                                @Html.DropDownList("pm", (List<SelectListItem>)ViewBag.PM, "All PM", new { @class = "m-wrap medium form-control searchfilterpm" })
                            </div>
                                }

                        <div class="col-md-2 pull-right text-right padding-top5">
                            <label>
                                @Html.CheckBox("selfWFH", false, new { @class = "m-wrap medium searchfilter", @value = CurrentUser.Uid })
                                <b class="text-blue">My Request </b>
                            </label>
                        </div>
                            }
                        }
                    }
                    else
                    {
                        <div class="col-md-2 pull-right text-right padding-top5 hidden">
                            <label>
                                @Html.CheckBox("selfWFH", true, new { @class = "m-wrap medium searchfilter", @value = CurrentUser.Uid })
                                <b class="text-blue">My Request</b>
                            </label>
                        </div>
                    }
                </div>


            </div>

        </div>
       @* <div id="LeaveBalance">
        </div>*@
        @*<div id="div_holidayType" class="form-group clearfix">

        </div>*@
        <table id="grid-NormalWFH" class="display postable table table-stats table-condensed"></table>
    </div>
</div>

@section scripts{

    <script src="~/Scripts/CustomJS/WFH/Index.js" asp-append-version="true"></script>
}