EMS.Website/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using EMS.Data;
using EMS.Service;
using EMS.Web.Code.Attributes;
using DataTables.AspNet.Core;
using EMS.Core;
using EMS.Web.Code.LIBS;
using EMS.Dto;
using System.Globalization;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using NUglify.Helpers;

namespace EMS.Web.Controllers
{
    //[CustomAuthorization()]
    public class ProjectController : BaseController
    {
        #region "Fields & Constructor"

        private readonly IUserLoginService userLoginService;
        private readonly IProjectService projectService;
        private readonly IDepartmentService departmentService;
        private readonly ITechnologyService technologyService;
        private readonly IVirtualDeveloperService virtualDeveloperService;
        private readonly IPreferenceService preferenceService;

        public ProjectController(IUserLoginService userLoginService, IVirtualDeveloperService virtualDeveloperService, IProjectService projectService, IDepartmentService departmentService, ITechnologyService technologyService, IPreferenceService preferenceService)
        {
            this.projectService = projectService;
            this.departmentService = departmentService;
            this.technologyService = technologyService;
            this.virtualDeveloperService = virtualDeveloperService;
            this.userLoginService = userLoginService;
            this.preferenceService = preferenceService;
        }

        #endregion

        [HttpGet]
        [CustomActionAuthorization]
        public ActionResult Index()
        {
            ProjectIndexDto projectViewModel = new ProjectIndexDto();
            projectViewModel.IsSuperAdmin = CurrentUser.IsSuperAdmin ? true : false;
            projectViewModel.IsHR = CurrentUser.RoleId == (int)Enums.UserRoles.HRBP ? true : false;
            var StatusList = from Enums.ProjectStatus p in Enum.GetValues(typeof(Enums.ProjectStatus)) select new { Name = p.ToString(), Id = (char)p };
            projectViewModel.ProjectStatusList = StatusList.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString(),
            }).ToList();

            if (CurrentUser.RoleId == (int)Enums.UserRoles.HRBP)
            {
                projectViewModel.PMList = userLoginService.GetPMAndPMOUsers(true).Select(x => new SelectListItem
                {
                    Value = x.Uid.ToString(),
                    Text = x.Name,

                }).ToList();
            }
            return View(projectViewModel);
        }

        [HttpPost]
        [CustomActionAuthorization]
        public IActionResult Index(IDataTablesRequest request, string ddl_status, string txt_search, string ddlPMList)
        {

            var pagingServices = new PagingService<Project>(request.Start, request.Length);
            var expr = PredicateBuilder.True<Project>();


            if (CurrentUser.RoleId == (int)Enums.UserRoles.PM || CurrentUser.RoleId == (int)Enums.UserRoles.PMO)

            {
                CurrentUser.PMUid = CurrentUser.Uid;
            }
            if (CurrentUser.RoleId == (int)Enums.UserRoles.HRBP)
            {
                if (!string.IsNullOrEmpty(ddlPMList))
                {
                    int pmUID = Convert.ToInt32(ddlPMList);
                    expr = expr.And(e => e.PMUid == pmUID || e.ProjectOtherPm.Any(po => po.Pmuid == pmUID));

                }
            }
            else
            {
                expr = expr.And(e => e.PMUid == CurrentUser.PMUid || e.ProjectOtherPm.Any(po => po.Pmuid == CurrentUser.PMUid));
            }
            if (!string.IsNullOrEmpty(ddl_status))
            {
                expr = expr.And(e => e.Status.Equals(ddl_status));
            }
            if (!string.IsNullOrEmpty(txt_search))
            {
                bool isId = false;
                isId = txt_search.All(char.IsDigit);
                if (isId)
                {
                    int crmId = Convert.ToInt32(txt_search);
                    expr = expr.And(e => e.CRMProjectId.Equals(crmId));
                }
                else
                {
                    expr = expr.And(e => e.Name.Contains(txt_search));
                }

            }

            pagingServices.Filter = expr;
            pagingServices.Sort = (o) =>
            {
                foreach (var item in request.SortedColumns())
                {
                    switch (item.Name)
                    {
                        case "Name":
                            return o.OrderByColumn(item, c => c.Name);

                        default:
                            return o.OrderByColumn(item, c => c.ModifyDate);

                    }
                }
                return o.OrderByDescending(c => c.ModifyDate);
            };
            int totalCount = 0;
            var response = projectService.GetProjectsByPaging(out totalCount, pagingServices);
            return DataTablesJsonResult(totalCount, request, response.Select((r, index) => new
            {
                r.ProjectId,
                rowIndex = (index + 1) + (request.Start),
                ClientId = r.ClientId == null ? "Client : N/A" : "Client : " + r.ClientId + "<br/><b>" + r.Client.Name + "</b>",
                Name = string.IsNullOrEmpty(r.Name) ? "N/A" : r.Name + "<br/>EMS Project ID : <b>" + r.ProjectId + "</b>&nbsp;(CRM ID : <b>" + r.CRMProjectId + "</b>)",
                Model = r.BucketModel.ModelName,
                r.ActualDevelopers,
                Status = string.Format("{0} ({1})", Common.GetProjectDisplayStatus(r.Status), r.ProjectDevelopers.Count(p => p.WorkStatus == (int)Enums.ProjectDevWorkStatus.Running))
            }));
        }

        [HttpGet]
        [CustomActionAuthorization]
        public ActionResult AddEditProject(int? id)
        {

            ProjectDto projectViewModel = new ProjectDto();

            projectViewModel.DepartmentList = departmentService.GetActiveDepartments().OrderBy(x => x.Name).Select(x => new DropdownListDto
            {
                Text = x.Name,
                Id = x.DeptId
            }).ToList();

            projectViewModel.TechnologyList = technologyService.GetTechnologyList().Where(x => x.IsActive == true).OrderBy(y => y.Title).
                      Select(z => new DropdownListDto
                      {
                          Id = z.TechId,
                          Text = z.Title
                      }).ToList();

            projectViewModel.ModelList = projectService.GetBucketModels().Select(x => new SelectListItem
            {
                Text = x.ModelName,
                Value = x.BucketId.ToString()
            }).ToList();
            var statusList = from Enums.ProjectStatus p in Enum.GetValues(typeof(Enums.ProjectStatus)) select new { Text = p.ToString(), Id = (char)p };
            projectViewModel.ProjectStatusList = statusList.Select(x => new SelectListItem
            {
                Text = x.Text,
                Value = x.Id.ToString()
            }).ToList();
            if (id != null)
            {
                Project project = projectService.GetProjectById(Convert.ToInt32(id));
                if (project != null)
                {
                    projectViewModel.ProjectId = project.ProjectId;
                    projectViewModel.ActualDevelopers = project.ActualDevelopers;
                    projectViewModel.Name = project.Name;
                    projectViewModel.CRMId = project.CRMProjectId;
                    projectViewModel.BillingTeam = project.BillingTeam;
                    projectViewModel.ClientId = project.ClientId;

                    projectViewModel.Model = Convert.ToInt32(project.Model);
                    projectViewModel.EstimatedDays = Convert.ToInt32(project.EstimateTime);
                    projectViewModel.Notes = project.Notes;
                    projectViewModel.ProjectDetailsDoc = project.ProjectDetailsDoc;
                    projectViewModel.StartDate = project.StartDate.HasValue ? project.StartDate.Value.ToString("dd/MM/yyyy") : null;
                    projectViewModel.Status = project.Status;
                    projectViewModel.IsInHouse = project.IsInHouse;

                    if (project.Project_Department.Count > 0)
                    {
                        projectViewModel.DepartmentList.ForEach(x =>
                        {
                            if (project.Project_Department.Any(y => y.Department.DeptId == x.Id))
                            {
                                x.Selected = true;
                            }
                        });
                    }

                    if (project.Project_Tech.Count > 0)
                    {
                        projectViewModel.TechnologyList.ForEach(x =>
                        {
                            if (project.Project_Tech.Any(y => y.Technology.TechId == x.Id))
                            {
                                x.Selected = true;
                            }
                        });
                    }
                }

            }
            return View(projectViewModel);
        }

        [HttpPost]
        [CustomActionAuthorization]
        public ActionResult AddEditProject(ProjectDto projectViewModel, IFormFile ProjectDetailsDoc)
        {
            if (CurrentUser != null && CurrentUser.Uid != 0 && ModelState.IsValid)
            {
                bool success = false;
                bool fileUploadError = false;
                bool isClientExist = true;
                Project project = new Project();
                if (projectViewModel.ProjectId != 0)
                {
                    project = projectService.GetProjectById(projectViewModel.ProjectId);
                }

EMS.Website/Views/Project/AddEditProject.cshtml
@using System.Web.Mvc
@using EMS.Core
@model ProjectDto
@using EMS.Web.Code.LIBS
<div class="main_content clearfix">
    <div class="full-wdth clearfix padding20">
        @Html.Partial("_Notification")
        <div class="manageProject-Page full-wdth clearfix">
            <h2>Edit Project</h2>
            <div class="create-form-outer-box dis-block clearfix">
                <div class="grey-bg ems-form dis-block clearfix">
                    @using (Html.BeginForm("AddEditProject", "Project", FormMethod.Post, new { @id = "addEditProjectForm", @enctype = "multipart/form-data" }))
                    {
                        @Html.HiddenFor(model => model.ProjectId)
                        @Html.Hidden("IsInHouseOld", Model.IsInHouse)
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.Name)
                                </div>
                                <div class="col-lg-7">
                                    @Html.TextBoxFor(model => model.Name, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.CRMId)
                                </div>
                                <div class="col-lg-3">
                                    @Html.TextBoxFor(model => model.CRMId, null, new { @class = "form-control", @maxlength = "8" })
                                </div>
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.EstimatedDays)
                                </div>
                                <div class="col-lg-3">
                                    @Html.TextBoxFor(model => model.EstimatedDays, new { @class = "form-control", @maxlength = "4" })
                                </div>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.Model)
                                </div>
                                <div class="col-lg-7">
                                    @Html.DropDownListFor(model => model.Model, Model.ModelList, "--Select Model--", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.ActualDevelopers)
                                </div>
                                <div class="col-lg-3">
                                    @Html.TextBoxFor(model => model.ActualDevelopers, new { @class = "form-control", @maxlength = "4" })
                                </div>
                                @if (Model.ProjectId != 0)
                                {
                                    <div class="col-md-2">
                                        @Html.LabelFor(model => model.ClientId)
                                    </div>
                                    <div class="col-lg-3">

                                        @Html.TextBoxFor(model => model.ClientId, new { @class = "form-control", @maxlength = "5" })

                                    </div>
                                }
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.Status)
                                </div>
                                <div class="col-lg-7">
                                    @Html.DropDownListFor(model => model.Status, Model.ProjectStatusList, "--Select--", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.StartDate)
                                </div>
                                <div class="col-lg-3">
                                    @Html.TextBoxFor(model => model.StartDate, "{0:dd/MM/yyyy}", new { @class = "form-control" })

                                </div>
                                <div class="col-md-2"><label for="StartDate" style="float:left" class="error"></label></div>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.BillingTeam)
                                </div>
                                <div class="col-lg-7">
                                    @Html.DropDownListFor(model => model.BillingTeam,  new List<SelectListItem>
                           {

                               new SelectListItem { Text="UK",Value="UK"},
                               new SelectListItem { Value="USA", Text="USA"},
                               new SelectListItem { Value="AUS", Text="Australia"},
                               new SelectListItem { Value="INRFL", Text="India FL"},
                               new SelectListItem { Value="INR", Text="India"},
                               new SelectListItem { Value="Fr" ,Text="France"},
                               new SelectListItem { Value="UAE" ,Text="UAE"}

                           }, "--Select--", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.Notes)
                                </div>
                                <div class="col-lg-8">
                                    @Html.TextAreaFor(model => model.Notes, new { @class = "form-control", @style = "width:100%; resize:none;min-height:50px;" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.ProjectDetailsDoc)
                                </div>
                                <div class="col-md-7">
                                    <input type="file" name="ProjectDetailsDoc" />

                                    @*@Html.TextBoxFor(model => model.ProjectDetailsDoc, new { @type = "file",@name="file" })*@

                                    <p style="font-size:smaller">(Upload only *.pdf,*.doc,*.docx,*.zip and *.rar file)</p>
                                </div>

                                @*<div class="col-md-8">

                    </div>*@

                            </div>
                            <div class="col-md-6">
                                @if (Model.ProjectDetailsDoc != null)
                                {
                                    <div class="col-md-2">
                                        @Html.Label("Uploaded Files:")
                                    </div>
                                    <div class="col-md-7">
                                        <a title="view file content" href="javascript:void(0)" onclick="window.open('Content/ProjectDoc/@Model.ProjectDetailsDoc', '_blank', 'location=yes,height=570,width=520,scrollbars=yes,status=yes');">
                                            @Model.ProjectDetailsDoc
                                        </a>
                                    </div>

                                }
                            </div>
                            <div class="col-md-6">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.IsInHouse)
                                </div>
                                <div class="col-md-7">
                                    @Html.CheckBoxFor(model => model.IsInHouse)
                                </div>
                            </div>
                        </div>

                        <div class="row margin-top20">

                            <div class="col-md-12">
                                <div>
                                    <div class="hds">Department:</div>
                                </div>
                            </div>



                            <div class="col-lg-12 deptChkBox">

                                @if (Model.DepartmentList != null)
                                {
                                    foreach (var dept in Model.DepartmentList)
                                    {
                                        @*@Html.CheckBoxListFor(Model.Department, @Model.DepartmentList,)*@
                                        <div class="col-md-3">

                                            @if (Model.DepartmentList.Any(x => x.Id == dept.Id && x.Selected == true))
                                            {

                                                <input type="checkbox" name="Department" id="dept_@dept.Id" data-id="@dept.Id" value="@dept.Id" checked="@dept.Selected" />
                                            }
                                            else
                                            {
                                                <input type="checkbox" name="Department" id="dept_@dept.Id" data-id="@dept.Id" value="@dept.Id" />
                                            }


                                            <label for="dept_@dept.Id" style="font-size: 13px;">&nbsp; @dept.Text</label>
                                        </div>
                                    }

                                }
                            </div>
                        </div>
                        <div class="row margin-top20">
                            <div class="col-md-12">

                                <div>
                                    <div class="hds">Technology:</div>
                                </div>

                            </div>

                            <div class="col-lg-12 ">
                                @if (Model.TechnologyList != null)
                                {
                                    foreach (var tech in Model.TechnologyList)
                                    {
                                        <div class="col-md-3">

                                            @if (Model.TechnologyList.Any(x => x.Id == tech.Id && x.Selected == true))
                                            {
                                                <input type="checkbox" name="Technology" id="tech_@tech.Id" data-id="@tech.Id" value="@tech.Id" checked="@tech.Selected" />
                                            }
                                            else
                                            {
                                                <input type="checkbox" name="Technology" id="tech_@tech.Id" data-id="@tech.Id" value="@tech.Id" />
                                            }


                                            <label for="tech_@tech.Id">&nbsp; @tech.Text</label>
                                        </div>
                                    }
                                }
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-md-12 margin-top20">
                                <button type="submit" id="btn-Submit" class="btn btn-custom pull-left" value="Save">Save</button>
                                <a href="@Url.Action("Index","Project")" class="btn btn-custom pull-left margin-left10">Cancel</a>
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{   
    <script src="~/Scripts/CustomJS/Project/index.js"></script>

}

EMS.Website/Views/Project/_AddAdditionalSupport.cshtml
@using System.Web.Mvc
@using EMS.Web.Models.Others
@model ProjectAdditionalSupportDto

@using (Html.BeginForm("RequestAdditionalSupport", "Project", FormMethod.Post, new { @id = "additionalSupportForm" }))
{
    Html.RenderPartial("_ModalHeader", new ModalHeader { Heading = "Request Additional Support", DisplayCloseButton = false });

    <div class="modal-body">
        @{ Html.RenderPartial("_Notification"); }
        <div id="validation-summary"></div>
        @Html.HiddenFor(x => x.FromProjectStatus)
        @Html.HiddenFor(x => x.Status)
        @foreach (var id in Model.AssignedUserIds)
        {
            <input type="hidden" name="AssignedUserIds[]" value="@id" />
        }

        <div class="row form-group">
            <div class="col-md-2">
                @Html.LabelFor(model => model.ProjectId)
            </div>
            <div class="col-md-10">

                @Model.ProjectName
                @Html.HiddenFor(model => model.ProjectId)

            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2">
                <label>Project Manager </label>
            </div>
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.TLid,  Model.TLList, "Select PM", new { @class = "form-control",  @data_rule_required = "true" })
            </div>
            <div class="col-md-4 padding-top15">
                <label class="label label-danger">Project Manager is mandatory</label>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2">
                <label>Reason for Add. Support</label>
            </div>
            <div class="col-md-10">
                @*@Html.TextAreaFor(model => model.Description,  htmlAttributes: new { @class = "form-control", @data_msg_required = "Reason for Add. Support is required", @data_rule_required = "true" })*@
                @Html.TextAreaFor(model => model.AddDescription, htmlAttributes: new { @class = "form-control", @data_msg_required = "Reason for Add. Support is required", @data_rule_required = "true" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2">
                <label>Start Date for Add. Support</label>
            </div>
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.StartDate,  htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div class="col-md-2">
                <label>End Date for Add. Support</label>
            </div>
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.EndDate,  htmlAttributes: new { @class = "form-control datepicker", @readonly = "readonly" })
            </div>
        </div>

    </div>

    <div class="modal-footer">
        <button id="CancelAdditionalSupport" class="btn btn-custom pull-right" type="button">Cancel</button>
        <button class="btn btn-custom btn-pink pull-right margin-right10" id="SubmitAddSupport" type="submit">SUBMIT</button>
        <button class="btn btn-custom btn-pink pull-left" id="SubmitAddSupportContinue" type="submit">SKIP AND CONTINUE</button>
    </div>
}

EMS.Website/Views/Project/_AddEditProjectDeveloper.cshtml
@using EMS.Web.Models.Others
@{
    Layout = null;
}


<div class="addedit-addEditProjectDeveloper">


    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "Add/Edit Project Developer(s)" })

    <div class="modal-body">
        <div id="koProjectDeveloper">
            @using (Html.BeginForm("AddEditProjectDeveloper", "Project", FormMethod.Post, new { @id = "addEditDeveloperForm", data_bind = "submit:saveProjectDeveloper" }))
            {
                <div class="form-group">
                    <input type="hidden" id="hdnProjectId" value="@ViewBag.ProjectId" />
                    <div class="row margin-bottom20">
                        <div class="col-md-3">
                            <strong class="">Project Developer</strong>
                        </div>
                        <div class="col-md-3">
                            <strong>Virtual Developer</strong>
                        </div>
                        <div class="col-md-3">
                            <strong>Remark</strong>
                        </div>
                        <div class="col-lg-2">
                            <strong>Status</strong>
                        </div>
                        <div class="col-lg-1">
                            <strong>Action</strong>
                        </div>
                    </div>
                    <hr />
                    <div id="devModal-Process" style="text-align:center;display:none">
                        <img src="~/Content/images/blue-loading-gif-transparent-9.gif" width="50" height="50" />
                    </div>
                    <div data-bind="foreach:{data:ProjectDevelopers}">
                        <div class="row margin-bottom10">
                            <div class="col-md-3">
                                <select data-bind="options:$parents[0].ActualDevelopers,optionsText:'text',optionsValue:'value',optionsCaption:'--Select Developer--',value: Uid,attr:{'name':'ProjectDeveloperMapping['+$index()+'].Uid'}" class="form-control"></select>
                           
                            </div>
                            <div class="col-md-3">

                                <select data-bind="options:$parents[0].VirtualDevelopers,optionsText: 'text',optionsValue: 'value',optionsCaption:'--Virtual Developers--',value:VirtualDeveloperID,attr:{'name':'ProjectDeveloperMapping['+$index()+'].VirtualDeveloperID'}" class="form-control" required></select>
                            </div>
                            <div class="col-md-3">
                                @Html.TextArea("txtAreaRemark", new { data_bind = "value:Remark,attr:{'name':'ProjectDevelopingMapping['+$index()+'].Remark'}", @class = "form-control" })

                            </div>
                            <div class="col-md-2">
                                <select data-bind="options:$parents[0].StatusList,optionsText:'text',optionsValue:'value',value:Status,attr:{'name':'ProjectDeveloperMapping['+$index()+'].status'}" class="form-control"></select>
                            </div>
                            <div class="col-md-1">
                                <button class="btn btn-default AddNewProjectDeveloper" data-bind="click:$parent.addProjectDevelopers,visible:$parent.ProjectDevelopers().length==($index()+1)" type="button">
                                    <i class="fa fa-plus"></i>
                                </button>
                                <button class="btn btn-default" data-bind="click:$parent.removeProjectDeveloper,visible:$parent.ProjectDevelopers().length>1" type="button">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                    @await Html.PartialAsync("_ModalFooter", new ModalFooter { DefaultButtonCss = false, SubmitButtonID = "btn_SubmitProjectDev", SubmitButtonText = "Submit", CancelButtonText = "Cancel", OnlyCancelButton= !ViewBag.IsEditable })

            }
        </div>
        @* A quick brown fox jump over the lazy dog*@
    </div>


</div>