EMS.Website/Models/Calendar/CalendarDay.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EMS.Web.Models.Calendar
{
    public class CalendarDay
    {

        public DateTime Date { get; set; }
        public string Day { get; set; }
        public int? LeaveType { get; set; }
        public int LeaveId { get; set; }



        public List<KeyValuePair<string, int>> EmployeeWithLeaveId { get; set; }

        /// <summary>
        /// CalenderDayList : 
        /// 1 string    :   Employee Name
        /// 2 int       :   LeaveId
        /// 3 int       :   LeaveType (Normal[15] / Urgent[16])
        /// 4 int       :   LeaveStatus (Pending[6] / Approved[7] / Cancelled[8] / UnApproved[9])
        /// </summary>
        public List<Tuple<string, int, int, int>> CalenderDayList { get; set; }
        /// <summary>
        /// created 19/12/2018 for adjust leave hour
        /// 1 string    :   Employee Name
        /// 2.int       :   LateHoureId
        /// 3.string    :   LateHour
        /// 4.string    :   EarlyLeave
        /// </summary>
        public List<Tuple<string, int, string, string,string>> CalenderDayAdjustHourList { get; set; }
    }
}

EMS.Website/Models/Calendar/CalendarForMultipleMonths.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EMS.Web.Models.Calendar
{
    public class CalendarForMultipleMonths
    {
        public CalendarForMultipleMonths()
        {
            CalendarMonths = new List<CalendarMonth>();
        }
        public DateTime startDate { get; set; }
        public List<CalendarMonth> CalendarMonths { get; set; }
    }
}

EMS.Website/Models/Calendar/CalendarMonth.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EMS.Web.Models.Calendar
{
    public class CalendarMonth
    {
        public CalendarMonth()
        {
            LocumCalendarDays = new List<CalendarDay>();
        }
        public List<CalendarDay> LocumCalendarDays { get; set; }
        public string MonthName { get; set; }

    }
}

EMS.Website/Models/Calendar/CalendarMonthWithWeek.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EMS.Web.Models.Calendar
{
    public class CalendarMonthWithWeek
    {
        public CalendarMonthWithWeek()
        {
            calendarWeeks = new List<MonthWeek>();
        }
        public List<MonthWeek> calendarWeeks { get; set; }
        public string MonthName { get; set; }

        public bool DisablePrevious { get; set; }
    }
}

EMS.Website/Models/Calendar/CalendarMultipleMonthsByWeek.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EMS.Web.Models.Calendar
{
    public class CalendarMultipleMonthsByWeek
    {
        public CalendarMultipleMonthsByWeek()
        {
            CalendarMonths = new List<CalendarMonthWithWeek>();
        }
        public DateTime startDate { get; set; }
        public int PharmacyId { get; set; }
        public List<CalendarMonthWithWeek> CalendarMonths { get; set; }
    }
}

EMS.Website/Models/Calendar/CalendarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EMS.Web.Models.Calendar
{
    public class PharmacyCalendarViewModel
    {
        public PharmacyCalendarViewModel()
        {
            CalendarViews = new List<CalendarViewModel>();
            HeaderCalendarDates = new List<EmployeeCalendarDate>();
        }
        public List<CalendarViewModel> CalendarViews { get; set; }
        public string MonthName { get; set; }

        public List<EmployeeCalendarDate> HeaderCalendarDates { get; set; }
    }

    public class CalendarViewModel
    {
        public CalendarViewModel()
        {
            EmployeeCalendarDates = new List<EmployeeCalendarDate>();
            CalendarEmployees = new List<CalendarEmployee>();
        }
        public string Month { get; set; }
        public string TeamName { get; set; }
        public List<EmployeeCalendarDate> EmployeeCalendarDates { get; set; }        
        public List<CalendarEmployee> CalendarEmployees { get; set; }
        public bool LoadBaseCss { get; set; }
    }

    public class CalendarDatesModel
    {
        public bool Leave { get; set; }
        public bool IsSunday { get; set; }
        public bool IsPlanned { get; set; }
        public bool IsHalfDay { get; set; }
        public TimeSpan StartTime { get; set; }
        //public bool StartHalfDay { get; set; }
        //public bool EndHalfDay { get; set; }
        //public bool StartHalfDayType { get; set; }
        //public bool EndHalfDayType { get; set; }
        public bool IsScheduleCover { get; set; }       
        public string CalendarDate { get; set; }
        public byte LeaveStatus{ get; set; }
        public bool IsLocum { get; set; }
        public bool IsPublicHoliday { get; set; }
        public bool IsDayOff { get; set; }
        public TimeSpan OverTimeStart { get; set; }
        public TimeSpan OverTimeEnd { get; set; }
        public bool IsOverTime { get; set; }
        public byte Status { get; set; }
    }

    public class CalendarEmployee
    {
        public CalendarEmployee()
        {
            EmployeeCalendarDates = new List<EmployeeCalendarDate>();
        }
        public string Name { get; set; }
        public bool IsSelf { get; set; }
        public string JobTitle { get; set; }
        public List<EmployeeCalendarDate> EmployeeCalendarDates { get; set; }
    }

    public class EmployeeCalendarDate
    {
        public string Day { get; set; }
        public int DateDay { get; set; }
        public string LeaveCssClass { get; set; }
        public string HeaderCssClass { get; set; }
        public string LeaveInfoToolTip { get; set; }
    }
}

EMS.Website/Models/Calendar/JobDataCount.cs
namespace EMS.Web.Models.Calendar
{
    public class JobDataCount
    {
        public int Count { get; set; }

        public string ColorCode { get; set; }

        public string JobIds { get; set; }

        public int StatusType { get; set; }
    }
}

EMS.Website/Models/Calendar/MonthWeek.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EMS.Web.Models.Calendar
{
    public class MonthWeek
    {
        public MonthWeek()
        {
            calendarDays = new List<CalendarDay>();
        }
        public List<CalendarDay> calendarDays { get; set; }
    }
}

EMS.Website/Controllers/LeaveController.cs
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using EMS.Core;
using EMS.Data;
using EMS.Dto;
using EMS.Dto.SARAL;
using EMS.Service;
using EMS.Service.SARAL;
using EMS.Service.SARALDT;
using EMS.Web.Code.Attributes;
using EMS.Web.Code.LIBS;
using EMS.Web.Controllers;
using EMS.Web.Models;
using EMS.Web.Models.Calendar;
using EMS.Website.Code.LIBS;
using EMS.Website.LIBS;
using EMS.Website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using static EMS.Core.Enums;

namespace EMS.Website.Controllers
{
    public class LeaveController : BaseController
    {
        #region "Fields"

        private IUserLoginService userLoginService;
        private ILeaveService leaveService;
        private ILevAllotmentService levAllotmentService;
        private ILevDetailsService levDetailsService;
        private ILevMonthdetService levMonthdetService;
        private ILevAllotmentDTService levAllotmentDTService;
        private ILevDetailsDTService levDetailsDTService;
        private ILevMonthdetDTService levMonthdetDTService;
        private IWFHService wFHService;
        public int leaveadlust = 0;
        public int leaveadlustid = 0;
        string logPath = "D:/local/EMSWebCore/EMS.Website/wwwroot/Leave_Log/leave-log.txt";
        public bool isPreviousMonth = false;
        #endregion

        #region "Constructor"

        public LeaveController(IWFHService _wFHService, IUserLoginService _userLoginService, ILeaveService _manageLeaveService, ILevAllotmentService _levAllotmentService, ILevDetailsService _levDetailsService, ILevMonthdetService _levMonthdetService, ILevAllotmentDTService _levAllotmentDTService, ILevDetailsDTService _levDetailsDTService, ILevMonthdetDTService _levMonthdetDTService)
        {
            this.userLoginService = _userLoginService;
            this.leaveService = _manageLeaveService;
            this.levAllotmentService = _levAllotmentService;
            this.levDetailsService = _levDetailsService;
            this.levMonthdetService = _levMonthdetService;
            this.levAllotmentDTService = _levAllotmentDTService;
            this.levDetailsDTService = _levDetailsDTService;
            this.levMonthdetDTService = _levMonthdetDTService;
            this.wFHService = _wFHService;
        }

        #endregion
            
        [CustomActionAuthorization]
        public ActionResult Index()
        {
            bool IsPmHrPmo = (RoleValidator.HR_RoleIds.Contains(CurrentUser.RoleId) || CurrentUser.RoleId == (int)Enums.UserRoles.PM
                || RoleValidator.TL_Technical_DesignationIds.Contains(CurrentUser.DesignationId)
            || RoleValidator.TL_QualityAnalyst_DesignationIds.Contains(CurrentUser.DesignationId)
            || RoleValidator.TL_DigitalMarketing_DesignationIds.Contains(CurrentUser.DesignationId)
            || RoleValidator.TL_UIUX_DesignationIds.Contains(CurrentUser.DesignationId)
            || RoleValidator.TL_ARVRUnityGaming_DesignationIds.Contains(CurrentUser.DesignationId)
            || RoleValidator.TL_Sales_DesignationIds.Contains(CurrentUser.DesignationId)
            || RoleValidator.TL_ITInfra_DesignationIds.Contains(CurrentUser.DesignationId)
            || RoleValidator.TL_AccountsandAdmin_DesignationIds.Contains(CurrentUser.DesignationId)
            || RoleValidator.TL_HR_DesignationIds.Contains(CurrentUser.DesignationId)
                //  || RoleValidator.DV_RoleIds.Contains(CurrentUser.RoleId)
                ) ? true : false;
            ViewBag.Users = GetEmployees(false);
            if (!IsPmHrPmo)
            {
                ViewBag.LeaveCategory = GetLeaveCategoryByGender(CurrentUser.Gender, false);
            }
            else
            {
                ViewBag.LeaveCategory = GetLeaveCategory(false);
            }
            //ViewBag.LeaveCategory = GetLeaveCategory(false);
            ViewBag.Status = typeof(Enums.LeaveStatus).EnumToDictionaryWithDescription().Select(v => new SelectListItem { Text = v.Key, Value = v.Value.ToString() }).ToList();
            ViewBag.LeaveType = typeof(Enums.LeaveType).EnumToDictionaryWithDescription().Where(v => v.Value == 15 || v.Value == 16).Select(v => new SelectListItem { Text = v.Key, Value = v.Value.ToString() }).ToList();
            ViewBag.PM = userLoginService.GetPMAndPMOHRDirectorUsers(true).Select(p => new SelectListItem { Text = p.Name, Value = p.Uid.ToString() }).ToList();
            //ViewBag.PM = userLoginService.GetPMAndPMOUsers(true).Select(p => new SelectListItem { Text = p.Name, Value = p.Uid.ToString() }).ToList();

            return View();
        }

        [HttpPost]
        [CustomActionAuthorization]
        public IActionResult GetLeaves(IDataTablesRequest request, SpecialSearchFilterViewModel searchFilter)
        {
            TempData.Put("searchFilter", searchFilter);

            DateTime dateStart, dateEnd;

            var pagingService = new PagingService<LeaveActivity>(request.Start, request.Length);

            var expr = PredicateBuilder.True<LeaveActivity>();

            int pmId = (CurrentUser.RoleId == (int)Enums.UserRoles.PM || CurrentUser.RoleId == (int)Enums.UserRoles.UKPM || CurrentUser.RoleId == (int)Enums.UserRoles.PMO) ? CurrentUser.Uid : CurrentUser.PMUid;
            if (CurrentUser.Uid > 0)
            {
                if (CurrentUser.RoleId == (int)UserRoles.PM || CurrentUser.RoleId == (int)UserRoles.UKPM || CurrentUser.RoleId == (int)UserRoles.PMO || CurrentUser.RoleId == (int)UserRoles.UKBDM)
                {
                    expr = expr.And(e => e.Uid == CurrentUser.Uid || (e.UserLogin1.PMUid.HasValue && e.UserLogin1.PMUid.Value == pmId) || (e.UserLogin1.TLId.HasValue && e.UserLogin1.TLId.Value == pmId));
                }
                else if (RoleValidator.TL_Technical_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_QualityAnalyst_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_DigitalMarketing_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_UIUX_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_ARVRUnityGaming_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_ITInfra_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_Sales_DesignationIds.Contains(CurrentUser.DesignationId)
                      || RoleValidator.TL_AccountsandAdmin_DesignationIds.Contains(CurrentUser.DesignationId)
                    //|| RoleValidator.DV_RoleIds.Contains(CurrentUser.RoleId)
                    )
                {
                    int[] sdList = userLoginService.GetTLUsers(CurrentUser.Uid).Select(T => T.Uid).ToArray();
                    expr = expr.And(e => e.Uid == CurrentUser.Uid || (e.UserLogin1.TLId.HasValue && e.UserLogin1.TLId.Value == CurrentUser.Uid) || (sdList.Contains((int)e.UserLogin1.TLId))
                    );
                }
                //else if (RoleValidator.TL_RoleIds.Contains(CurrentUser.RoleId) || RoleValidator.DV_RoleIds.Contains(CurrentUser.RoleId))
                //{
                //    int[] sdList = userLoginService.GetTLUsers(CurrentUser.Uid).Select(T => T.Uid).ToArray();
                //    expr = expr.And(e => e.Uid == CurrentUser.Uid || (e.UserLogin1.TLId.HasValue && e.UserLogin1.TLId.Value == CurrentUser.Uid) || (sdList.Contains((int)e.UserLogin1.TLId))
                //    );
                //}
                else
                {
                    if (!RoleValidator.HR_RoleIds.Contains(CurrentUser.RoleId))
                    {
                        expr = expr.And(e => e.Uid == CurrentUser.Uid);
                    }

                }
            }

            if (searchFilter.user.HasValue && searchFilter.user.Value != 0)
            {
                expr = expr.And(l => l.Uid == searchFilter.user.Value);
            }
            if (searchFilter.status.HasValue && searchFilter.status.Value != 0)
            {
                expr = expr.And(l => l.Status == searchFilter.status.Value);
            }
            if (searchFilter.leavecatagory.HasValue && searchFilter.leavecatagory.Value != 0)
            {
                expr = expr.And(l => l.LeaveCategory == searchFilter.leavecatagory.Value);
            }
            if (searchFilter.leavetype.HasValue && searchFilter.leavetype.Value != 0)
            {
                expr = expr.And(l => l.LeaveType == searchFilter.leavetype);
            }
            if (searchFilter.pm.HasValue && searchFilter.pm.Value != 0)
            {
                expr = expr.And(l => (l.UserLogin1.PMUid == searchFilter.pm) || (l.UserLogin1.TLId == searchFilter.pm));
            }
            if (!string.IsNullOrEmpty(searchFilter.startDate) && DateTime.TryParseExact(searchFilter.startDate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out dateStart))
            {
                expr = expr.And(l => l.StartDate >= dateStart || l.EndDate >= dateStart);
            }
            if (!string.IsNullOrEmpty(searchFilter.endDate) && DateTime.TryParseExact(searchFilter.endDate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out dateEnd))
            {
                expr = expr.And(l => l.EndDate <= dateEnd || l.StartDate <= dateEnd);
            }

            pagingService.Filter = expr;

            pagingService.Sort = (o) =>
            {
                foreach (var item in request.SortedColumns())
                {
                    switch (item.Name)
                    {
                        case "UserName":
                            return o.OrderByColumn(item, c => c.UserLogin1.Name);

                        case "Status":

EMS.Website/Views/Leave/AdjustHours.cshtml
@using EMS.Core
@model AdjustHoursDto
@{
    ViewBag.Title = "AdjustHours";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles{
    <style>
        .table .form-control.inpt-wd4 {
            margin-left: 127px;
            width: 100px;
            margin-top: -35px;
        }

        .altform.adjust-table .row {
            margin: 0 0 10px 0;
        }

        .adjust-table .table .form-control.inpt-wd4 {
            margin: 0 15px 0 15px;
            display: inline-block;
        }

        input[type=checkbox], input[type=radio] {
            margin: 12px 10px 16px;
            margin-top: 1px\9;
            line-height: normal;
        }
    </style>
}
<div class="main_content clearfix">
    <div class="full-wdth clearfix padding20">
        @Html.Partial("_Notification")
        <div class="timesheet-page full-wdth clearfix">
            <div id="tackCommentMessageDiv" class="alert alert-success alert-dismissable" style="display:none"></div>
            <h2>Adjust Hours</h2>
            <div class="create-form-outer-box dis-block clearfix">
                <div class="form-wdth1 dis-block clearfix">
                    <div class="grey-bg ems-form dis-block clearfix validateform altform adjust-table">
                        @using (Html.BeginForm("AdjustHours", "Leave", FormMethod.Post, new { id = "adjustform" }))
                        {
                            <div class="table-custom timesheet-table table-responsive clearfix">
                                <div class="row">
                                    <div class="col-md-4 ">
                                        <div class="col-md-6">
                                            <label>Day of Date :</label>
                                        </div>
                                        <div class="col-md-6">
                                            @Html.TextBoxFor(x => x.Modified, "{0:dd/MM/yyyy}", new { @class = "form-control", @readonly = "readonly", required = "required" })
                                        </div>
                                    </div>
                                </div>
                                <table class="table" id="LeaveAdjustTable">
                                    <thead>
                                        <tr>
                                            <th style="width:2%;">#</th>
                                            <th style="width:20%;">Employee Name</th>
                                            <th style="width:78%;">Type</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                            if (CurrentUser.RoleId == (int)Enums.UserRoles.PM || CurrentUser.RoleId == (int)Enums.UserRoles.UKBDM || CurrentUser.RoleId == (int)Enums.UserRoles.PMO)
                            {
                                <div class="row">
                                    <button type="submit" class="btn btn-custom pull-right txtbtnSave" name="Save">Save</button>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="divoverlay hide"></div>
@section scripts{
    <script src="~/Scripts/masked-input/jquery.maskedinput.min.js"></script>
    <script src="~/Scripts/datepicker/moment.js"></script>
    <script src="~/Scripts/CustomJS/Leave/AdjustHours.js" asp-append-version="true"></script> 
}

EMS.Website/Views/Leave/Calendar.cshtml
@using EMS.Web.Models.Others
@using EMS.Core
@model EMS.Dto.LeaveActivityDto
@{
    ViewBag.Title = "Leave Calendar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
    <link href="~/css/select2.css" rel="stylesheet" />
    <link href="~/content/scroll/skins.css" rel="stylesheet" />
}

<div class="main_content clearfix">
    <div class="full-wdth clearfix padding20">
        @await Html.PartialAsync("_Notification")

        <div class="ManageDepartment-page full-wdth clearfix">
            <div class="box-body">
                <div class="row">
                    <div class="full">
                        <div class="pull-left col-md-2">
                            <h2>Leaves Calender</h2>
                        </div>
                        <div class="col-md-10 search-filter pull-right">
                            <div class="row form-group">
                                <div class="col-md-12">
                                    @Html.ActionLink("Apply Leave", "manageleave", "leave", new { returnview = "calendar" }, new { @class = "btn btn-custom pull-right margin-right10" })
                                    <a href="@Url.Action("index", "leave")" class="btn btn-custom pull-right margin-right10">List View</a>
                                    <div class="col-md-2 pull-right">
                                        <select id="leaveType" class="form-control leaveType">
                                            <option value="0" selected="selected">Normal and Urgent Leave</option>
                                            <option value="15">Normal Leave</option>
                                            <option value="16">Urgent Leave</option>
                                            @if (CurrentUser.RoleId == (int)Enums.UserRoles.PMO || CurrentUser.RoleId == (int)Enums.UserRoles.UKBDM@*|| CurrentUser.RoleId == (int)Enums.UserRoles.PM*@)
{
<option value="1">Late Hour</option>
<option value="2">UnAuthorized</option>
}
                                        </select>
                                    </div>
                                    @if (ViewBag.UnderEmployeeList != null)
                                    {
                                        if (ViewBag.UnderEmployeeList.Count > 0)
                                        {
                                        <div class="col-md-2 pull-right @ViewBag.UnderEmployeeList!=null' ">

                                            <select id="Uid" class="form-control">
                                                <option value="0">All Employee</option>
                                                @foreach (var item in ViewBag.UnderEmployeeList)
                                                {
                                                    <text>
                                                        <option value="@item.Value">@item.Text</option>
                                                    </text>
                                                }
                                            </select>

                                        </div>
                                        }
                                    }
                                    else
                                    {
                                        @Html.Hidden("Uid")
                                    }

                                    @if (CurrentUser.RoleId != (int)Enums.UserRoles.UKBDM && CurrentUser.RoleId != (int)Enums.UserRoles.UKPM && CurrentUser.RoleId != (int)Enums.UserRoles.AUPM && CurrentUser.RoleId != (int)Enums.UserRoles.PMOAU && CurrentUser.RoleId != (int)Enums.UserRoles.PMO)
                                    {
                                        @if (ViewBag.LeaveCategory != null)
                                        {
                                            <div class="col-md-2 pull-right @ViewBag.LeaveCategory!=null' ">

                                                <select id="leaveCategory" class="form-control">
                                                    <option value="0">All Leave</option>
                                                    @foreach (var item in ViewBag.LeaveCategory)
                                                    {
                                                        <text>
                                                            <option value="@item.Value">@item.Text</option>
                                                        </text>
                                                    }
                                                </select>

                                            </div>
                                        }
                                        else
                                        {
                                            @Html.Hidden("LeaveCategory")
                                        }
                                    }
                                    @if (ViewBag.PmList != null)
                                    {
                                        <div class="col-md-2 pull-right">
                                            <select id="PmId" class="form-control ">
                                                <option value="0">All PM</option>
                                                @foreach (var item in ViewBag.PmList)
                                                {
                                                    <text>
                                                        <option value="@item.Uid">@item.Name</option>
                                                    </text>
                                                }
                                            </select>

                                        </div>
                                    }
                                    else
                                    {
                                        @Html.Hidden("PmId", (Object)ViewBag.PmId)
                                    }                                    
                                    @if (RoleValidator.HR_RoleIds.Contains(CurrentUser.RoleId) || CurrentUser.RoleId == (int)Enums.UserRoles.PM || CurrentUser.RoleId == (int)Enums.UserRoles.UKPM || CurrentUser.RoleId == (int)Enums.UserRoles.PMO
                                       || RoleValidator.TL_Technical_DesignationIds.Contains(CurrentUser.DesignationId)
                                       || RoleValidator.TL_QualityAnalyst_DesignationIds.Contains(CurrentUser.DesignationId)
                                       || RoleValidator.TL_DigitalMarketing_DesignationIds.Contains(CurrentUser.DesignationId)
                                       || RoleValidator.TL_UIUX_DesignationIds.Contains(CurrentUser.DesignationId)
                                       || RoleValidator.TL_ARVRUnityGaming_DesignationIds.Contains(CurrentUser.DesignationId)
                                       || RoleValidator.TL_ITInfra_DesignationIds.Contains(CurrentUser.DesignationId)
                                       || RoleValidator.TL_Sales_DesignationIds.Contains(CurrentUser.DesignationId)
                                       //|| RoleValidator.DV_RoleIds.Contains(CurrentUser.RoleId) 
                                       || CurrentUser.RoleId == (int)Enums.UserRoles.UKBDM)
                                    {
                                        <div class="col-md-1 pull-right text-right padding-top5">
                                            <label>
                                                @Html.CheckBox("selfleave", false, new { @class = "m-wrap medium searchfilter", @value = CurrentUser.Uid }) <b class="text-blue">My Leave</b>
                                            </label>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="col-md-1 pull-right text-right padding-top5 hidden">
                                            <label>
                                                @Html.CheckBox("selfleave", true, new { @class = "m-wrap medium searchfilter", @value = CurrentUser.Uid }) <b class="text-blue">My Leave</b>
                                            </label>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="LeaveBalance">
                </div>
            </div>
            <div id="calendardiv">
                @await Component.InvokeAsync("LeaveCalender", new { leaveType = 0 })
            </div>
        </div>
        <div class="divoverlay">
            @*<img src="@(SiteKey.DomainName+"images/ProgressWheel.gif")" />*@
        </div>
    </div>
</div>
@await Html.PartialAsync("_Modal", new Modal { ID = "modal-leave-detail", AreaLabeledId = "modal-leave-detail-label", Size = Enums.ModalSize.Large })

@section scripts{
    <script src="~/Content/scroll/baron.js"></script>
    <script src="~/Content/scroll/script.js"></script>
    <script src="~/Scripts/CustomJS/leave/leaveCalender.js" asp-append-version="true"></script>
}